name: Test It

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test Me
    runs-on: ubuntu-latest
    steps:
      - name: Self test
        uses: ./
        id: self-test
        with:
          show-logging: true
